import React from "react";
import * as S from "./partner.style.ts";
import { emailAddress } from "../../constants.ts";

const Partner = () => {
  return (
    <S.Wrapper>
      <S.Section>
        <S.Title>Partner with Simple Budgeting</S.Title>
        <br />
        <S.SubTitle>
          Empower Your Clients. Simplify Your Workflow. Grow Together.
        </S.SubTitle>
        <div>
          Simple Budgeting’s <strong>Partner Program</strong> is designed for{" "}
          <strong>financial advisors, coaches, and professionals</strong> who
          help clients take control of their finances. By partnering with us,
          you’ll get the tools, access, and support you need to guide your
          clients toward smarter financial decisions — all in one intuitive
          platform.
        </div>
      </S.Section>
      <S.Section>
        <S.SubTitle>Partner Benefits</S.SubTitle>
        <div>
          <div>
            <strong>Exclusive 50% Discount for Your Clients</strong>
          </div>
          Your clients receive{" "}
          <strong>50% off the Simple Budgeting Pro Plan</strong>, making it
          easier than ever for them to unlock premium features that help them
          budget smarter.
        </div>
        <div>
          <div>
            <strong>30-Day Free Trial</strong>
          </div>
          Every client gets a <strong>risk-free 30-day trial</strong> before
          payment begins — giving them time to explore, learn, and experience
          the value of the platform before committing.
        </div>
        <div>
          <div>
            <strong>Dedicated Admin Dashboard</strong>
          </div>
          As a partner, you’ll have access to a{" "}
          <strong>special admin account</strong> that allows you to:
        </div>
        <ul>
          <li>View your clients’ accounts in real time</li>
          <li>Monitor progress and budgeting behavior</li>
          <li>Offer targeted feedback and personalized guidance</li>
        </ul>
      </S.Section>
      <S.Section>
        <S.SubTitle>Seamless Client Onboarding</S.SubTitle>
        <div>
          Each partner receives a <strong>unique referral link</strong> that
          clients can use to sign up directly under your partnership account.
        </div>
        <div>
          This ensures all your clients are properly connected to your admin
          dashboard — no manual setup required.
        </div>
      </S.Section>
      <S.Section>
        <S.SubTitle>Flexible Data Entry Options</S.SubTitle>
        <div>
          Your clients — or you, as their advisor — can easily add budget data
          in whichever way fits best:
        </div>
        <div>
          <strong>For Clients:</strong>
        </div>
        <ul>
          <li>
            Upload data using a{" "}
            <strong>CSV file generated by Simple Budgeting</strong>, or
          </li>
          <li>
            Manually input income and expenses directly in the{" "}
            <strong>Simple Budgeting UI</strong>
          </li>
        </ul>
        <div>
          <strong>For Admins:</strong>
        </div>
        <ul>
          <li>
            Upload client budgets in bulk via <strong>CSV</strong>, or
          </li>
          <li>
            Manually enter data on behalf of clients for a hands-on, guided
            setup
          </li>
        </ul>
      </S.Section>
      <S.Section>
        <S.SubTitle>Why Partner with Simple Budgeting</S.SubTitle>
        <ul>
          <li>Simplify how you manage client budgets</li>
          <li>Strengthen client accountability and engagement</li>
          <li>Reduce back-and-forth with seamless data sharing</li>
          <li>Help clients track goals, habits, and spending with clarity</li>
          <li>Grow your advisory services with a modern, affordable tool</li>
        </ul>
      </S.Section>
      <S.Section className="last">
        <S.SubTitle>Start Your Partnership Today</S.SubTitle>
        <div>
          Join a growing network of financial professionals using Simple
          Budgeting to transform how clients think about money.
        </div>
        <div>
          Become a Partner today by contacting us at{" "}
          <a href={`mailto:${emailAddress}`}>{emailAddress}</a>
        </div>
      </S.Section>
    </S.Wrapper>
  );
};

export default Partner;
